### ISSUE TITLE
Dynamic detection limit

### ISSUE THREAD

**Issue by DavidZong** [ppreshant/WW-CoV2-project#39]
If the DI, Blank, and NTCs are not clean. The detection limit needs to be elevated.

**Comment by DavidZong** [comment]
From our discussion:

New LOD: 3 droplets + mean + (1.6 * SD) of all negative controls (DI, BLANK, NTC) for a given plate.

**Comment by DavidZong** [comment]
working branch for this issue is 

https://github.com/ppreshant/WW-CoV2-project/tree/%2336-bayou

**Comment by DavidZong** [comment]
https://github.com/ppreshant/WW-CoV2-project/commit/8873aa02e23baac9bdbb478bf1bf033969355f6a

Prototype is up. Report can be found in https://docs.google.com/spreadsheets/d/1dBESjgWSFsOBodFFpYNhWIOAQ2a3wvoLkrn12V_rFck/edit#gid=92521305 in the newest sheet "1203-1208 Rice Bayou TEST manhole samples". See new columns Limit of detection and positivity.

**Comment by DavidZong** [comment]
TODO:

Add functionality to ignore Baylor files and ignore qPCR LODs

**Comment by ppreshant** [comment]
Why do we need to ignore Baylor files? Are we planning to run some of their
data in our pipeline?

Also since 2-calculations.. script is merging multiple files, we will need
to introduce a new variable to track the file id the sample is from
(qPCR,ddPCR or Baylor). If it's a case we expect to encounter, it might be
worth to code this.
